### ISSUE TITLE
Invalid object name 'Labyrinth.dbo.Item'.

### ISSUE THREAD

**Issue by vandomej** [mckenziegray/LabyrinthGame#2]
Hello!

I installed the project as per the steps below taken from the README. After following these steps, I thought that I would be able to run the project.

```

```

Unfortunately this is not the case. When I loaded the project in Visual Studio and ran it I got the following error.

```
System.Data.SqlClient.SqlException: 'Invalid object name 'Labyrinth.dbo.Item'.'
```

I'm sure that I meet the correct specifications for machine and environment as stated in the README.

```

```

My machine is a Windows 8 machine with an i7-3770 and i'm running Visual Studio 2017.

Call stack:
```
Labyrinth.dll!Labyrinth.Dao.GetTable(string tableName, string orderByColName) Line 36
Labyrinth.dll!Labyrinth.ItemDao.GetTable() Line 33
Labyrinth.dll!Labyrinth.ItemDao.GetData() Line 47
Labyrinth.dll!Labyrinth.Item.Item(Labyrinth.ItemType type) Line 32
Labyrinth.dll!Labyrinth.Item.RandomItem(System.Collections.Generic.IEnumerable<Labyrinth.Item> currentLoot) Line 85
Labyrinth.dll!Labyrinth.Location.Location(bool isRoom) Line 81
Labyrinth.dll!Labyrinth.Maze.Maze(int size) Line 25
Labyrinth.dll!Labyrinth.Game.Game(int startingDifficulty) Line 51
Labyrinth.dll!Labyrinth.Program.Main(string[] args) Line 13
```

**Comment by mckenziegray** [comment]
@vandomej Thanks for opening this issue! As you can tell by the tardiness of my reply, I haven't worked on this project for a while. The problem you identified should be fixed now, so you should be able to run from VS (2019 only) with no problem now. (However, this project is a work-in-progress, so some game features might not work.)
